# Generated by Django 3.0.6 on 2020-05-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('Department', models.CharField(max_length=40)),
                ('Dateodbirth', models.DateTimeField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
